"""Increase password field length 1000

Revision ID: c798a79f89be
Revises: f4c35f60fb44
Create Date: 2024-09-14 13:47:48.644056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c798a79f89be'
down_revision: Union[str, None] = 'f4c35f60fb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=1001),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=1001),
               existing_nullable=False)
    # ### end Alembic commands ###
